# only for dev group's hosts
---
enable_proxy: true
proxy_env:
  http_proxy: "socks5h://127.0.0.1:1080"
  https_proxy: "socks5h://127.0.0.1:1080"
  all_proxy: "socks5h://127.0.0.1:1080"

docker_proxy_url: "socks5h://localhost:1080"
docker_proxy_no_proxy_list: "localhost,127.0.0.1,docker-registry.somecorporate.com"
